# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alex Hilson
description:      'My personal writing covering a wide range of technologies, from geospatial analysis to web services to Docker.'
url:              http://alexhilson.co.uk
baseurl:          /

author:
  name:           'Alex Hilson'
  url:            https://github.com/AlexHilson

paginate:         1

# Custom vars
